apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: maven
  name: maven-application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: maven
    spec:
      containers:
      - image: geethika609/maven-web-application
        name: maven
        ports:
        - name: maven
          containerPort: 8080
